# klue.kr 데이터 가져오기!

In [16]:
import pandas as pd
import selenium as se
from selenium import webdriver

In [191]:
df=pd.read_csv("C:/Users/yangh/OneDrive - edy/Desktop/수신도우미/course_list.csv")

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1592 entries, 0 to 1591
Data columns (total 31 columns):
Unnamed: 0    1592 non-null int64
캠퍼스           1592 non-null object
대학이름          1592 non-null object
대학번호          1592 non-null int64
부서이름          1592 non-null int64
부서번호          1592 non-null int64
학수번호          1592 non-null object
분반            1592 non-null int64
학수번호-분반       1592 non-null object
이수구분          1592 non-null object
교과목명          1592 non-null object
담당교수          1494 non-null object
학점(시간)        1592 non-null object
강의시간/강의실      1519 non-null object
상대평가          178 non-null object
인원제한          1581 non-null object
대기            1581 non-null object
교환학생          1281 non-null object
출석확인자율화       434 non-null object
무감독시험         48 non-null object
유연학기          6 non-null object
1)M           1 non-null object
2)FC          20 non-null object
3)T           23 non-null object
1학년 정원        1584 non-null object
2학년 정원        1584 non-null object
3학년 정원        1584 non-null object
4학년 정원        1584 non-null object
교환학생 정원       1584 non-null float64
대학원생 정원       1584 non-null object
전체 정원         1584 non-null object
dtypes: float64(1), int64(5), object(25)
memory usage: 385.7+ KB

In [182]:
df.head(10)

,Unnamed: 0,캠퍼스,대학이름,대학번호,부서이름,부서번호,학수번호,분반,학수번호-분반,이수구분,...,1)M,2)FC,3)T,1학년 정원,2학년 정원,3학년 정원,4학년 정원,교환학생 정원,대학원생 정원,전체 정원
0,0,서울,정보대학,5720,6666,6666,BNCS301,0,BNCS301-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,5.0,-,35 + 5
1,1,서울,정보대학,5720,6666,6666,BNCS303,0,BNCS303-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,5.0,-,35 + 5
2,2,서울,정보대학,5720,6666,6666,BNCS411,0,BNCS411-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,3.0,-,22 + 3
3,0,서울,정보대학,5720,5965,5965,STEP410,0,STEP410-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,0.0,-,60 + 0
4,1,서울,정보대학,5720,5965,5965,STEP411,0,STEP411-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,0.0,-,60 + 0
5,2,서울,정보대학,5720,5965,5965,STEP412,0,STEP412-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,0.0,-,60 + 0
6,3,서울,정보대학,5720,5965,5965,STEP413,0,STEP413-00,전공필수,...,NaN,NaN,NaN,-,-,-,-,0.0,-,60 + 0
7,0,서울,정보대학,5720,5944,5944,ISEC401,0,ISEC401-00,전공선택,...,NaN,NaN,NaN,-,-,-,-,1.0,-,24 + 1
8,0,서울,정보대학,5720,5722,5722,COSE211,1,COSE211-02,전공선택,...,NaN,NaN,NaN,-,-,-,-,13.0,-,87 + 13
9,1,서울,정보대학,5720,5722,5722,COSE211,2,COSE211-02,전공선택,...,NaN,NaN,NaN,-,-,-,-,13.0,-,87 + 13

In [192]:
df['교과목명'] = df['교과목명'].str.split(" ", n = 1, expand = True)[0]
df.iloc[:5,10]

0    뇌및인지과학개론(영강)
1     뇌및의공학입문(영강)
2    뇌및머신러닝입문(영강)
3           현장실습V
4          현장실습VI
Name: 교과목명, dtype: object

In [193]:
df.loc[df['교과목명'].str.contains("(영강)"),'교과목명'] = df.loc[df['교과목명'].str.contains("(영강)"),'교과목명'].str.split("(", n = 1, expand = True)[0]

In [194]:
df.iloc[:20,10]

0     뇌및인지과학개론
1      뇌및의공학입문
2     뇌및머신러닝입문
3        현장실습V
4       현장실습VI
5      현장실습VII
6     현장실습VIII
7       고급해킹실습
8         이산수학
9         이산수학
10        자료구조
11        자료구조
12        자료구조
13        알고리즘
14        알고리즘
15        계산이론
16        논리설계
17        논리설계
18        논리설계
19       컴퓨터구조
Name: 교과목명, dtype: object

In [197]:
df=df.dropna(subset=['교과목명'])
df=df.dropna(subset=['담당교수'])

In [198]:
df.isnull().sum()

Unnamed: 0       0
캠퍼스              0
대학이름             0
대학번호             0
부서이름             0
부서번호             0
학수번호             0
분반               0
학수번호-분반          0
이수구분             0
교과목명             0
담당교수             0
학점(시간)           0
강의시간/강의실        65
상대평가          1327
인원제한            11
대기              11
교환학생           294
출석확인자율화       1061
무감독시험         1446
유연학기          1490
1)M           1493
2)FC          1474
3)T           1471
1학년 정원           8
2학년 정원           8
3학년 정원           8
4학년 정원           8
교환학생 정원          8
대학원생 정원          8
전체 정원            8
dtype: int64

In [202]:
df.shape

(1494, 31)

In [40]:
webdriver_path = 'C:/Users/yangh/Documents/chromedriver_win32/chromedriver'
driver = webdriver.Chrome(webdriver_path)

url='https://klue.kr/'
driver.get(url)

In [63]:
temp_num=len(driver.find_elements_by_class_name("lecture-search-result"))
temp_num

2

In [112]:
temp_num_1=len(driver.find_elements_by_class_name("lecture-search-result"))
temp_num_1

for i in range(temp_num_1):
    temp_xpath="""/html/body/app-root/lecture-result/div/lecture-list/div/div["""+str(i+3)+"""]/div[2]/div[2]/a/button"""
    driver.find_element_by_xpath(temp_xpath).click()
    temp_num_2=len(driver.find_elements_by_class_name("lecture-detail-content"))
    for j in range(temp_num_2):
        temp_xpath_2="""/html/body/app-root/lecture-view/div/lecture-eval/div/div["""+str(j+2)+"""]/div[1]/div[2]"""
        print(driver.find_element_by_xpath(temp_xpath_2).text)
    print('\n')
    driver.execute_script("window.history.go(-1)")

사실 경영전략은 어느 분반을 들어도 할게 많고 어려운 과목이라 문정빈 교수님의 수업이 특히 힘들다고 보기는 어려울 것 같습니다. 다만 교수님의 강의력이 정말 좋고, 어려운 내용도 학생들이 이해할 수 있도록 풀어서 설명해 주시는 점, 그리고 교수님께서도 강의 준비를 철저히 해오시는 점 등으로 인해 한 학기 동안 배울 수 있는 것이 굉장히 많은 수업이라고 생각합니다.
다만 팀 프로젝트가 두 번 있는 수업이기 때문에 팀원을 잘 만나시는 것이 굉장히 중요할 것이라고 생각합니다. 아무래도 독강 보다는 아는 사람과 함께 수강하는 게 한 학기 동안 편하실 것이라고 생각이 듭니다.
두 번의 팀 프로젝트 모두 교수님께서 주제를 던져 주시고, 팀원들끼리 상의하여 어떤 주제를 선정해서 발표할 지 정하면 됩니다. 그리고 해당 주제에 맞추어 5개 정도의 question을 교수님이 미리 주시기 때문에 이 question들에 대한 답을 위주로 발표를 준비하시면 됩니다. 두 번째 팀 프로젝트는 발표 이후 10장 내외의 레포트 또한 제출해야합니다.
중간, 기말고사 모두 보는데, 객관식과 서술형으로 문제가 주어집니다. 객관식은 강의 내용에서 주로 나오며, 난이도가 별로 높지 않습니다. 서술형은 질문 4개 정도가 제시되는데, 서술형이 차지하는 비중이 높으니 서술형에 맞추어 공부를 하시는 것이 좋을 것 같습니다.
강의 중 질문을 자주 하는 것이 participation에 들어가고, 이 participation 점수가 20점 가까이를 차지하니, 영어에 자신이 있으신 분들은 자주 하는 것이 좋을 것 같습니다.다만 점수에 반영이 많이 되는 까닭에 particpation이 굉장히 치열하니, 수업 시간에 손 열심히 들으세요!
경영전략은 경영학에서 지금까지 배운 모든 것을 포괄하는 과목이다 보니 빡셀 수밖에 없는 것 같습니다! 그러나 문정빈 교수님의 경전 수업은 한 학기 동안 열심히 하면 배워갈 수 있는 것이 많은 수업이라고 생각합니다! 다들 화이팅하세요
스윗하시고 경전 치고는 가볍게 들을만 한 것 같다..
에이쁠은 일단 손들고 질문을 많이 한 사람에게만 가는듯 시험을 완전 잘보지 않는 이상?
경영전략 치고는 널널하다. 라고 생각됩니다.

출첵은 조교님이 시작할때, 끝날때 항상 하시고 모든 경전이 그렇듯 참여형 수업이라 손을 많이 드시는 것이 좋습니다. 그러나 아예 질문하지 않는 사람도 많아요.
중간 기말은 객관식과 서술형이 섞여 나오는데 공부를 조금만 해도 그리 어렵진 않습니다. 팀플은 총 두 번 있고 팀을 학기 초에 자리를 앉은대로 짜기 때문에 이 때 일찍 나와서 자리를 잡는 것이 좋습니다. 교수님이 친절하시고 영어도 잘하시고 지식도 많으셔서 전체적으로 만족스러웠습니다.
교수님이 열정이 넘치십니다.

항상 밝은 톤으로 수업을 재밌게 이끌어 가주세요!

발표 많이 하면 학점을 잘 받을 수 있는것 같습니다
쏘쏘. 일단 시험에서 나오는 서술형들이 많이 어려워요. 많이 어려운데 어떻게 써야될지 감이 안옴. 팀플 중요합니다. 팀플 잘못하면 에이이상 받기 힘들어요. 그리고 손들고 의견 개진 많이하삼. 다다익선임
교수님께서 너무 깔끔하게 강의를 잘해주십니다
팀플 2번에 중간고사 기말고사
출석체크는 매일 조교님이 수업 시작과 끝에 하시고
중간고사는 진도를 살짝 너무 빨리 빼셔서 공부양(암기량)은 적진 않았지만
중간이후로는 파이널 발표가 많기 때문에 기말고사 공부 부담은 훨씬 적었습니다

시험 양식은 객관식 60점에 서술형 40점
서술형도 교재 미니케이스 기반으로 내셔서 미니케이스 잘 읽고 관련 질문들 생각해서 가면 무리없이 풀 수 있습니다
발표점수 별도로 있어서 수업 시간에 적극적으로 질문해야합니다


경전인데 작은 팀플 하나 큰 팀플 하나 이렇게 두 개뿐이라 양은 적은 편입니다. 지난 학기엔 특히 교수님이 다른 프로젝트로 바쁘셔서 수업에 거의 신경을 못 쓰신 것 같아요. 덕분에 수업에서 배운 건 없지만 팀플을 견디긴 편했습니다.
Pick good teammates and you’ll be fine.
Exams were not hard.
It wasnt THAT demanding. I didnt really learn much and got by easily with an A
지정좌석제로 출석체크하고 팀플 두번 중간 기말 있었습니다
팀플때문에 한 학기 많은 시간 보내지만...좋은 팀원 만나서 나름 재미있게 스트레스 받지 않고 잘 지냈어요! 팀원은 자리에 앉은 구역을 중심으로 정해집니다. 미리미리 가서 자리 잡는 것 추천드려요! 그리고 중간, 기말 다 있는데 서술형 문제가 난이도가 있었어욤.... ㅜㅜ 케이스 다룬 것들 잘 공부해두시고 다른 팀 발표하는 것 유의해서 들으세요! 다 나와요!!!! 교수님 항상 웃고 있으세요 ㅋㅋㅋㅋㅋ
무난한 경영전략 강의입니다. 대부분의 경전이 적극적인 참여를 요하다보니 영어 스피킹이 다소 부족한 입장에서 반강제적으로 선택한 강의중심의 수업입니다.

다 괜찮은데 딱 하나 불만이었던게 수업때 교과서보다도 필수적인 하버드 비즈니스 리뷰 리포트를 거의 10개가량 각자 사야합니다. 보통은 한 그룹에 8~9명이라 나눠서 사는데요. 수업 초반에 누군가가 강의 전체 단톡방을 건의해서 클래스 전체가 공유했으면 어땠을까 싶기도 합니다. 리뷰 하나당 만원남짓이라 다하면 만만한 비용은 아닌데 시험범위에 포함되어서 부담되거든요. 특히 협조적이지 않은 그룹을 만나면 소수 혹은 단독으로 십만원 남짓을 부담해야 하거든요.

그외에는 전반적으로 만족스러운 강의였습니다. 교수님 젠틀하시고 교과서적이십니다. 따로 오피스 찾아가서 질문하고 도움요청해도 다 친절하게 들어주세요. 팀을 잘 만났다면 더 좋았을텐데라는 아쉬움이 남는 강의입니다. 독강이시면 가능한 앞자리의 적극적인 학생들괸 팀을 맺으세요.
경영전략 치고는 팀플은 적은 것 같았습니다.
시험은 수업 잘 안듣고 책만 열심히 보면 객관식은 잘 맞을 수 있어요,,,,
아 기말고사는 발표에서 나오기 때문에 책이랑 연결시켜서 공부해야 해요!!
저는 진짜 시험 공부 3일 정도 했는데 다행히 너무 좋은 팀을 만나서 성적은 만족스러웠습니다.
팀플 두번에 중간,기말 모두 있습니다. 교수님께서 퀄리티있는 팀플을 원하시고 활발한 발표를 장려하셔서 마냥 쉬운 강의는 아니지만 유익한 시간이었습니다.
경영전략을 가장 스탠다드하게 배울 수 있었던 과목인거 같습니다.
이 강의를 듣고 전략컨설팅쪽 커리어도 해보고싶다는 생각이 들었어요. 열심히 하려는 마음만 있으시면
강추드립니다.
팀플 2개
시험문제 어렵지 않지만 좋은 성적을 따기 쉽지 않아
영어 아주 잘하시는 분에게 추천
다른 경영전략에 비해서 인풋이 적어요. 하지만 중간고사 때 시험범위가 매우 넓어요. 중간 범위가 책 12단원 중 8단원이었나 그랬어요. 학점은 잘 주시는 편이신 것 같아요. 팀플은 2번만 하시면 되고, 팀원이 9명이기에 큰 부담이 있지는 않아요. 중간 때는 객관식이 매우 쉽고, 주관식이 어려웠어요. 기말엔 객관식, 주관식 모두 어려웠어요.
자신감 있는 교수님, 깔끔한 수업자료 덕분에 편하게 많은 것을 배울 수 있었습니다. 수업보다 조가 더 중요해요. 조를 잘 만나서 수업들으면서 재밌었습니다.
경영학과 수업이 대부분 내용이 붕 뜬 수업들이 많은데, 이 수업은 교수님 피드백도 날카롭고 수업 준비를 많이 하신 것이 눈에 보였습니다. 중간/기말 문제도 그랬고요.

적당히 할 것 많고, 학습부담량은 경전 치고 그리 많은 것 같진 않습니다.
경영학과에서 들은 수업 중 제일 좋았습니다!
교수님 정말 영어도 잘 하시고 박식하시고 수업도 잘 하시고ㅠㅠ 피드백도 정말 좋았어요.
팀플 두 번에 중간 기말 다 있어서 빡세긴 했지만, 경전이라 납득했습니다.
특히 팀플 발표가 준비하는 만큼 결과물이 나오고 남는 게 있었던 것 같아 매우 보람찼습니다.
출석: 지정좌석제로 매 수업 조교님이 들어오셔서 출석체크하시고 가십니다.

난이도: 교수님이 팀플 발표할 때 질문 많이 하시고 학우분들도 질문 잘하셔서 꼼꼼하게 준비해가야 합니다. 시험 난이도는 적당한 편.

학습량: 경전답게 팀플 이렇게 많이 해본 적 처음이었습니다. 다행히 좋은 분들 만나서 수월하게 했음. 시험은 개인적으로 기말고사보다 중간고사가 훨씬 어려웠다고 느꼈습니다. 하루 정도는 투자해야 좋은 점수 받을 수 있을 거 같습니다.

학점: 잘 주시는 거 같습니다. 팀플 평균이상/발표 여러번/중간고사 점수 미디안보다 조금 위/기말고사 점수 미디안보다 훨씬 높게 받았더니 A+나왔습니다.

성취감: 교수님 강의력이 좋으신 편. 경전 과목 특성상 뭘 배우는 느낌은 없지만 재밌게 들은 강의.
워크로드가 극악으로 유명한 경영전략 강의치고 나름 수월하게 들은 강의같습니다!
솔직히 교수님 강의는 귀에 잘 안들어옵니다...굳이 시험을 치기 위해서 열심히 들을 필요도 없는 거 같구요. 중간고사까지는 교수님이 수업진도를 많이 빼셔서 양이 엄청 많아서 좀 고생했던 기억이 나네요ㅠ 중간고사 끝나고 부터는 팀플발표가 주를 이뤄서 강의안 범위는 많지 않지만 학생들이 발표했던 PPT양이 좀 많아서 당황했었습니다. 시험은 객관식(60점)+서술형(40점)으로 구성되는데, 솔직히 책 안보고 교수님이 블랙보드에 올려주시는 강의안과 PPT만으로 공부해도 괜찮습니다. 하지만 중간중간에 헷갈리는 문제들이 꽤 있으므로 꼼꼼히 보시는게 좋을 것 같네요. 팀플은 학생 8~9명으로 구성해서 총 2개의 팀플을 하는데, 주제는 교수님이 미리 정해두신 것 중에서 사다리를 타서 팀별로 배분을 합니다. 무엇보다 팀원들 잘 짜시는게 굉장히 중요합니다. 저는 좋은 팀원들을 만나서 고생도 덜 하고 다들 화목하게 잘 마무리한 것 같네요. 2번째 팀플 때는 레포트도 제출해야 되는데 팀원들끼리 잘 배분하면 그렇게 양이 많지도 않았습니다.
중간(20%)+기말(25%)+참여도(20%)+팀플(35%) 로 구성되는데, 시험은 일단 평균이 60점대 일정도로 낮습니다. 그래서 교수님이 칼절평 안하고 비율을 약간 나누셔서 학점을 부여하는 것 같습니다. 중간은 좀 잘쳤는데 기말을 약간 못봤고, 팀플을 평타로 하고 솔직히 수업시간에 손들고 발표를 많이 해서 A+를 받은 것 같습니다...A 나올줄 알았는데...교수님이 약간 발표 열심히 하는 사람들 학점을 올려준 것 같습니다. 영어회화에 거리낌없이 참여하실 수 있다면 이 강의 추천드립니다. 영어를 잘 못해도 워크로드가 적은 경전으로도 추천드립니다!

In [209]:
col=['코드명+교수명','과목명','교수명','과목코드','이수구분','개설학기','학점','ID','총점','출석체크','학점','난이도','학습량','성취감','강의평']
data_list=[]
#len(df.index)
for i in range(len(df.index)):
    course=df.iloc[i,6]+' '+df.iloc[i,11]
    temp_url="https://klue.kr/lecture/search/"+df.iloc[i,6]+"%20"+df.iloc[i,11]
    driver.implicitly_wait(2)
    driver.get(temp_url)
    
    temp_num_1=len(driver.find_elements_by_class_name("lecture-search-result"))
    temp_num_1

    for i in range(temp_num_1):
        temp_xpath="""/html/body/app-root/lecture-result/div/lecture-list/div/div["""+str(i+3)+"""]/div[2]/div[2]/a/button"""
        driver.find_element_by_xpath(temp_xpath).click()
        new_input=[]
        new_input.append(course)
        #과목명
        new_input.append(driver.find_element_by_xpath('/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[1]').text)
        #교수명
        new_input.append(driver.find_element_by_xpath('/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[2]').text)
        #과목코드
        new_input.append(driver.find_element_by_xpath('/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[4]/table/tbody/tr[1]/td[2]').text)
        #이수구분
        new_input.append(driver.find_element_by_xpath('/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[4]/table/tbody/tr[2]/td[1]').text)
        #개설학기
        new_input.append(driver.find_element_by_xpath('/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[4]/table/tbody/tr[1]/td[1]').text)
        #학점
        new_input.append(driver.find_element_by_xpath('/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[4]/table/tbody/tr[3]/td[1]').text)
        #ID
        new_input.append("평균")
        #총점
        new_input.append(driver.find_element_by_xpath("""/html/body/app-root/lecture-view/div/lecture-info/div/div[1]/div[2]/div[3]/div/span[2]""").text)

        a=driver.find_element_by_tag_name('g')
        #출석체크
        new_input.append(a.find_elements_by_tag_name('text')[5].text)
        #학점
        new_input.append(a.find_elements_by_tag_name('text')[6].text)
        #난이도
        new_input.append(a.find_elements_by_tag_name('text')[7].text)
        #학습량
        new_input.append(a.find_elements_by_tag_name('text')[8].text)
        #성취감
        new_input.append(a.find_elements_by_tag_name('text')[9].text)
        #강의평
        new_input.append('-')

        data_list.append(new_input)
        driver.execute_script("window.history.go(-1)")

new_df=pd.DataFrame(data_list, columns=col)

StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=80.0.3987.87)

In [212]:
new_df=pd.DataFrame(data_list, columns=col)
new_df

,코드명+교수명,과목명,교수명,과목코드,이수구분,개설학기,학점,ID,총점,출석체크,학점,난이도,학습량,성취감,강의평
0,BNCS301 곽지현,신경및뇌공학(영강),곽지현 교수님,BMED404,전공선택,2018-2학기,3학점,평균,4.39,4.6,4.4,3,3.2,3.8,-
1,BNCS301 곽지현,뇌과학의이해(영강),곽지현 교수님,GEST120,교양,2016-1학기,3학점,평균,4.25,4.6,3.9,3.7,3.6,4.3,-
2,BNCS301 곽지현,뇌과학의이해(영강) 교양관310호에서 교양관409호로 강의실 변경,곽지현 교수님,GEST120,교양,2015-2학기,3학점,평균,4.50,5,4.2,3.7,4,4.2,-
3,BNCS301 곽지현,뇌과학의이해(영강),곽지현 교수님,GEST120,교양,2015-1학기,3학점,평균,4.40,4.8,3.9,3.8,3.6,4.2,-
4,BNCS301 곽지현,뇌과학의이해(영강),곽지현 교수님,GEST120,교양,2014-2학기,3학점,평균,4.38,4.8,4.2,3.9,3.8,4.1,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853,GERM237 전지선,독어어휘연습I(외국어강의),전지선 교수님,GERM237,전공선택,2018-1학기,3학점,평균,3.54,3.7,3.4,3.6,4.2,4.2,-
2854,GERM237 전지선,독어어휘연습I,전지선 교수님,GERM237,전공선택,2017-1학기,3학점,평균,4.23,4,4.1,3.8,4.2,4.4,-
2855,GERM237 전지선,독어어휘연습I,전지선 교수님,GERM237,전공선택,2016-1학기,3학점,평균,4.50,4.1,4.3,3.5,3.9,4.1,-
2856,GERM237 전지선,독어어휘연습I,전지선 교수님,GERM237,전공선택,2015-1학기,3학점,평균,4.29,3.9,3.6,3.6,4.1,4.3,-
2857,GERM237 전지선,독어어휘연습I 강의실 변경[14-03-18],전지선 교수님,GERM237,전공선택,2014-1학기,3학점,평균,3.43,예전 강의평가입니다,-,-,-,-,-

In [214]:
new_df.to_excel("C:/Users/yangh/OneDrive - edy/Desktop/수신도우미/평가초안.xlsx")

In [201]:
for i in range(20):
    course=df.iloc[i,6]+' '+df.iloc[i,11]
    print(course)

BNCS301 곽지현
BNCS303 이종환
BNCS411 감태의
STEP410 이성권
STEP411 이성권
STEP412 이성권
STEP413 이성권
ISEC401 김경곤
COSE211 박성빈
COSE211 박성빈
COSE213 이도길
COSE213 석흥일
COSE213 최수경
COSE214 박성빈
COSE215 이희조
COSE221 정성우
COSE221 백승준
COSE221 이숙윤
COSE312 오학주
COSE321 서태원

In [168]:
new_df

,강의명+교수명,과목코드,이수구분,개설학기,학점,ID,총점,출석체크,학점,난이도,학습량,성취감,강의평
0,경영전략 문정빈,BUSS402,전공필수,2019-2학기,3학점,총평균,4.14,4.9,3.7,3.6,3.9,4.1,-
1,경영전략 문정빈,BUSS402,전공필수,2019-1학기,3학점,총평균,4.00,4.8,3.8,3.4,3.9,3.8,-

In [205]:
driver.find_element_by_xpath("""/html/body/app-root/lecture-result/div/lecture-search/div/div[1]/div/input""").clear()